query
supportedTokens
	"Returns the collection of tokens supported by the receiver."

	^#(
		'brdrbar' 'brdrb' 'box' 'brdrbtw'
		'brdrdash' 'brdrdashsm' 'brdrdash' 'brdrdot'
		'brdrdashd' 'brdrdashdd' 'brdrdb' 'brdrth'
		'brdrwavydb' 'brdremboss' 'brdrengrave' 'brdrhair'
		'brdrl' 'brdrr' 'brdrcf' 'brdrsh'
		'brdrs' 'brsp' 'brdrdashdotstr' 'brdrtnthsg'
		'brdrtnthlg' 'brdrtnthmg' 'brdrthtnsg' 'brdrthtnlg'
		'brdrthtnmg' 'brdrtnthtnsg' 'brdrtnthtnlg' 'brdrtnthtnmg'
		'brdrt' 'brdrtriple' 'brdrwavy' 'brdrw'
	)